
module.exports = {
    FORMAT_TIME: "HH:mm DD/MM/YYYY",
    VI: "VI",
    EN: "EN",
    ADMIN: "ADMIN",
    USER: "USER",
    SUPPLIER: "SUPPLIER",
    TRONGGIO: "TRONGGIO",
    CHOXACNHAN_DATHANHTOAN: "CHOXACNHAN_DATHANHTOAN",
    CHOXACNHAN_CHUATHANHTOAN: "CHOXACNHAN_CHUATHANHTOAN",
    CHOLAYHANG_DATHANHTOAN: "CHOLAYHANG_DATHANHTOAN",
    CHOLAYHANG_CHUATHANHTOAN: "CHOLAYHANG_CHUATHANHTOAN",
    DANGSHIP_DATHANHTOAN: "DANGSHIP_DATHANHTOAN",
    DANGSHIP_CHUATHANHTOAN: "DANGSHIP_CHUATHANHTOAN",

    DON_HANG_MOI: "DON_HANG_MOI",
    GIAO_HANG_THANH_CONG: "GIAO_HANG_THANH_CONG",
    DON_HANG_DUOC_XAC_NHAN: "DON_HANG_DUOC_XAC_NHAN",
    DON_HANG_DANG_DUOC_GIAO: "DON_HANG_DANG_DUOC_GIAO",
    DON_HANG_BI_HUY: "DON_HANG_BI_HUY",
    HE_THONG: "HE_THONG",

    VANCHUYEN: "VANCHUYEN",
    GIAMGIA: "GIAMGIA",
    VOUCHERSHOP: "VOUCHERSHOP",
}