
module.exports = {
    VI: "VI",
    EN: "EN",
    ADMIN: "ADMIN",
    USER: "USER",
    SUPPLIER: "SUPPLIER",
    TRONGGIO: "TRONGGIO",
    CHOLAYHANG_DATHANHTOAN: "CHOLAYHANG_DATHANHTOAN",
    CHOLAYHANG_CHUATHANHTOAN: "CHOLAYHANG_CHUATHANHTOAN",
    DANGSHIP_DATHANHTOAN: "DANGSHIP_DATHANHTOAN",
    DANGSHIP_CHUATHANHTOAN: "DANGSHIP_CHUATHANHTOAN"
}